### ISSUE TITLE
登陆成功之后跳转callback页面失败

### ISSUE THREAD

**Issue by calanchenlins** [Bingjian-Zhu/Identity_Vue_Client#1]
vue的路由默认为hash模式， redirect_uri:设置为"http://localhost:5003/CallBack",会路由到"http://localhost:5003/CallBack/#/" 跳转到了HelloWorld页面。现在改为history模式，才可以跳转成功。想请教一下，你的例子是怎么跳转成功的。谢谢

**Comment by Bingjian-Zhu** [comment]
@calanchenlins 意思是你用这个demo跳转不成功对吗？然后改了路由模式才行对吧
